#!/bin/sh
# Written by Uwe Hermann <uwe@hermann-uwe.de>, released as public domain.
# Modified by Piotr Esden-Tempski <piotr@esden.net>, released as public domain.

# adapted for r0ket <http://r0ket.badge.events.ccc.de> development by
# Matthias Rampke <matthias@rampke.de>
# requires Homebrew <https://mxcl.github.com/homebrew>

# Stop if any command fails
set -e

##############################################################################
# Settings section
# You probably want to customize those
##############################################################################
PREFIX=$HOME/local
TARGET=arm-none-eabi		# Or: TARGET=arm-elf
[ -z $PREFIX ] && PREFIX=${HOME}/arm	# Install location of your final toolchain
[ -z $WORKDIR ] && WORKDIR=$PREFIX/work     #temporary directory
PARALLEL=			# Or: PARALLEL="-j 5" for 4 CPUs
# Set to 'sudo' if you need superuser privileges while installing
SUDO=''
# Set to 1 to be quieter while running
QUIET=0
# Set to 1 to use linaro gcc instead of the FSF gcc
USE_LINARO=0
# Set to 1 to enable C++
USE_CPP=0
# Make the gcc default to Cortex-M3
DEFAULT_TO_CORTEX_M3=1

##############################################################################
# Version and download url settings section
##############################################################################
if [ ${USE_LINARO} = 0 ] ; then
	# For FSF GCC:
	GCCVERSION=4.6.1
        if [ ${USE_CPP} = 0 ]; then
            GCC=gcc-core-${GCCVERSION}
            GCCDIR=gcc-${GCCVERSION}
        else
            GCC=gcc-${GCCVERSION}
            GCCDIR=${GCC}
        fi
        GCCURL=http://ftp.gnu.org/gnu/gcc/${GCCDIR}/${GCC}.tar.bz2
else
	# For the Linaro GCC:
	GCCRELEASE=4.6-2011.07
	GCCVERSION=4.6-2011.07-0
        GCC=gcc-linaro-${GCCRELEASE}
	GCCDIR=gcc-linaro-${GCCVERSION}
	GCCURL=http://launchpad.net/gcc-linaro/4.6/${GCCRELEASE}/+download/gcc-linaro-${GCCRELEASE}.tar.bz2
fi

BINUTILS=binutils-2.21.1
NEWLIB=newlib-1.19.0
GDB=gdb-7.0.1a
GMP=gmp-5.0.2
MPFR=mpfr-3.0.1
MPC=mpc-0.9

SHA1SUMS="525255ca6874b872540c9967a1d26acfbc7c8230  binutils-2.21.1.tar.bz2
8bf66f7a71534ba564563a0ba0b2517aead8ac30  gcc-4.6.1.tar.bz2
9b766705f051ffb7321de58f247688b0ae661b98  gcc-core-4.6.1.tar.bz2
828d99a63e0578879150f5681d234763cff69313  gcc-linaro-4.6-2011.07.tar.bz2
e57f2c7f93536ef54fab728eb733bf2c36550718  gdb-7.3.1.tar.bz2
3b2c0d50533bcf834c2da0a700dfc2f4852a07e4  gdb-7.0.1a.tar.bz2
2968220e1988eabb61f921d11e5d2db5431e0a35  gmp-5.0.2.tar.bz2
229722d553030734d49731844abfef7617b64f1a  mpc-0.9.tar.gz
fbf402fc196724ae60ef01eb6ca8490b1ea4db69  mpfr-3.0.1.tar.bz2
b2269d30ce7b93b7c714b90ef2f40221c2df0fcd  newlib-1.19.0.tar.gz"

##############################################################################
# Flags section
##############################################################################

if which getconf > /dev/null 2> /dev/null && getconf _NPROCESSORS_ONLN > /dev/null 2> /dev/null; then
	CPUS=$(getconf _NPROCESSORS_ONLN)
elif which sysctl > /dev/null 2> /dev/null && sysctl hw.ncpu 2> /dev/null > /dev/null; then
  CPUS=$(sysctl hw.ncpu | sed -E -e 's/^hw\.ncpu(: | = )//')
else
	CPUS=1
fi
PARALLEL=-j$((CPUS + 1))
echo "${CPUS} cpu's detected running make with '${PARALLEL}' flag"

GDBFLAGS=
BINUTILFLAGS=

if [ ${DEFAULT_TO_CORTEX_M3} = 0 ] ; then
	GCCFLAGS=
else
	# To default to the Cortex-M3:
	GCCFLAGS="--with-arch=armv7-m --with-mode=thumb --with-float=soft"
fi

# Pull in the local configuration, if any
if [ -f local.sh ]; then
    . ./local.sh
fi

MAKEFLAGS=${PARALLEL} ${MAKESILENT}
TARFLAGS=v
MAKESILENT=

if [ ${QUIET} != 0 ]; then
    TARFLAGS=
    MAKESILENT="-s"
fi

export PATH="${PREFIX}/bin:${PATH}"

SUMMON_DIR=${WORKDIR}
SOURCES=${SUMMON_DIR}/sources
STAMPS=${SUMMON_DIR}/stamps


##############################################################################
# OS and Tooldetection section
# Detects which tools and flags to use
##############################################################################

# normalized fetching with whatever we can find
if which fetch > /dev/null; then
    FETCHCMD="fetch -p"
elif which wget > /dev/null; then
    FETCHCMD="wget -c"
elif which curl > /dev/null; then
    FETCHCMD="curl -C - -O -L"
else
    FETCHCMD=ftp    # the only HTTP client on some BSD
fi

if [ USE_LINARO = 1 ]; then
    if which gnutar > /dev/null; then
        TAR=gnutar
    elif which gtar > /dev/null; then
        TAR=gtar
    else    # hopefully it understands the GNU format
        TAR=tar
    fi
else
    TAR=tar     # use the system tar
fi

if [ -z ${MAKE} ]; then
    if which gnumake > /dev/null; then
        export MAKE=gnumake
    elif which gmake > /dev/null; then
        export MAKE=gmake
    else
        export MAKE=make    # should be GNU make
    fi
fi

##############################################################################
# Building section
# You probably don't have to touch anything after this
##############################################################################

# Fetch a versioned file from a URL
dofetch() {
    if [ ! -e ${STAMPS}/$1.fetch ]; then
        log "Downloading $1 sources..."
        ${FETCHCMD} $2
        touch ${STAMPS}/$1.fetch
    fi
}

# Log a message out to the console
log() {
    echo "******************************************************************"
    echo "* $*"
    echo "******************************************************************"
}

# Unpack an archive
unpack() {
    log Unpacking $*
    # Use 'auto' mode decompression.  Replace with a switch if tar doesn't support -a
    ARCHIVE=$(ls ${SOURCES}/$1.tar.*)
    case ${ARCHIVE} in
	*.bz2)
	    echo "archive type bz2"
	    TYPE=j
	    ;;
	*.gz)
	    echo "archive type gz"
	    TYPE=z
	    ;;
	*)
	    echo "Unknown archive type of $1"
	    echo "leaving the decision to tar"
            TYPE=
	    ;;
    esac
    ${TAR} xf${TYPE}${TARFLAGS} ${SOURCES}/$1.tar.*

    # gdb-7.0.1a.tar.gz extracts to gdb-7.0.1, but the rest of the script
    # expects it to be gdb-7.0.1a
    if [ ! -d "$1" ]; then
        CLEANDIR=${1%[a-z]}
        if [ -d "$CLEANDIR" ]; then
            mv "$CLEANDIR" "$1"
        else
            echo "can't find files extracted for $1"
        fi
    fi
}

# Install a build
doinstall() {
    log $1
    ${SUDO} ${MAKE} ${MAKESILENT} $2 $3 $4 $5 $6 $7 $8
}

if [ ! -d $SUMMON_DIR ]; then
    mkdir -p ${SUMMON_DIR}
    SUMMON_DIR_CREATED=1
else
    SUMMON_DIR_CREATED=0
fi
mkdir -p ${STAMPS} ${SOURCES}

cd ${SOURCES}

dofetch ${BINUTILS} http://ftp.gnu.org/gnu/binutils/${BINUTILS}.tar.bz2
dofetch ${GCC} ${GCCURL}
dofetch ${NEWLIB} ftp://sources.redhat.com/pub/newlib/${NEWLIB}.tar.gz
dofetch ${GDB} http://ftp.gnu.org/gnu/gdb/${GDB}.tar.bz2
dofetch ${GMP} ftp://ftp.gmplib.org/pub/${GMP}/${GMP}.tar.bz2
dofetch ${MPFR} http://www.mpfr.org/${MPFR}/${MPFR}.tar.bz2
dofetch ${MPC} http://www.multiprecision.org/mpc/download/${MPC}.tar.gz

if which sha1sum > /dev/null; then
    for f in ${BINUTILS} ${GCC} ${NEWLIB} ${GDB} ${GMP} ${MPFR} ${MPC}; do
        ( echo "$SHA1SUMS" | grep -F $f | sha1sum -c - ) || ( log 'ERROR: Checksum fail!'; exit 1 )
    done
else
    log "WARING: skipping checksum checks due to missing sha1sum"
fi

cd ${SUMMON_DIR}

if [ ! -e build ]; then
    mkdir build
fi

if [ ! -e ${STAMPS}/${BINUTILS}.build ]; then
    unpack ${BINUTILS}
    cd build
    log "Configuring ${BINUTILS}"
    ../${BINUTILS}/configure --target=${TARGET} \
                           --prefix=${PREFIX} \
                           --enable-interwork \
                           --enable-multilib \
                           --with-gnu-as \
                           --with-gnu-ld \
                           --disable-nls \
                           --disable-werror \
			   ${BINUTILFLAGS}
    log "Building ${BINUTILS}"
    ${MAKE} ${MAKEFLAGS}
    doinstall ${BINUTILS} install
    cd ..
    log "Cleaning up ${BINUTILS}"
    touch ${STAMPS}/${BINUTILS}.build
    rm -rf build/* ${BINUTILS}
fi

if [ ! -e ${STAMPS}/${GCC}-boot.build ]; then
    unpack ${GCC} boot
    unpack ${GMP}
    mv ${GMP} ${GCCDIR}/gmp
    unpack ${MPFR}
    mv ${MPFR} ${GCCDIR}/mpfr
    unpack ${MPC}
    mv ${MPC} ${GCCDIR}/mpc
    cd build
    log "Configuring ${GCC}-boot"
    ../${GCCDIR}/configure --target=${TARGET} \
                      --prefix=${PREFIX} \
                      --enable-interwork \
                      --enable-multilib \
                      --enable-languages="c" \
                      --with-newlib \
                      --without-headers \
                      --disable-shared \
                      --with-gnu-as \
                      --with-gnu-ld \
                      --disable-nls \
                      --disable-werror \
		      --with-system-zlib \
		      ${GCCFLAGS}
    log "Building ${GCC}-boot"
    ${MAKE} ${MAKEFLAGS} all-gcc
    doinstall ${GCC}-boot install-gcc
    cd ..
    log "Cleaning up ${GCC}-boot"
    touch ${STAMPS}/${GCC}-boot.build
    rm -rf build/* ${GCCDIR}
fi

if [ ! -e ${STAMPS}/${NEWLIB}.build ]; then
    unpack ${NEWLIB}
    cd build
    log "Configuring ${NEWLIB}"
    # configuration options and flags partially
    # from https://github.com/jsnyder/arm-eabi-toolchain
    ../${NEWLIB}/configure --target=${TARGET} \
                         --prefix=${PREFIX} \
                         --enable-interwork \
                         --enable-multilib \
                         --with-gnu-as \
                         --with-gnu-ld \
                         --disable-nls \
                         --disable-werror \
                         --disable-newlib-supplied-syscalls \
			 --enable-newlib-io-long-long \
                         --disable-shared \
			 --with-float=soft
    log "Building ${NEWLIB}"
    NEWLIB_FLAGS="-ffunction-sections -fdata-sections -DPREFER_SIZE_OVER_SPEED -D__OPTIMIZE_SIZE__ -Os -g -fomit-frame-pointer -fno-unroll-loops -D__BUFSIZ__=256 -mabi=aapcs"
    ${MAKE} ${MAKEFLAGS} CFLAGS_FOR_TARGET="${NEWLIB_FLAGS}" CCASFLAGS="${NEWLIB_FLAGS}"
    doinstall ${NEWLIB} install
    cd ..
    log "Cleaning up ${NEWLIB}"
    touch ${STAMPS}/${NEWLIB}.build
    rm -rf build/* ${NEWLIB}
fi

# Yes, you need to build gcc again!
if [ ! -e ${STAMPS}/${GCC}.build ]; then
    unpack ${GCC}
    unpack ${GMP}
    mv ${GMP} ${GCCDIR}/gmp
    unpack ${MPFR}
    mv ${MPFR} ${GCCDIR}/mpfr
    unpack ${MPC}
    mv ${MPC} ${GCCDIR}/mpc
    cd build
    log "Configuring ${GCC}"
    [ ${USE_CPP} = 1 ] && GCCFLAGS="--enable-languages='c,c++' ${GCCFLAGS}"
    ../${GCCDIR}/configure --target=${TARGET} \
                      --prefix=${PREFIX} \
                      --enable-interwork \
                      --enable-multilib \
                      --with-newlib \
                      --disable-shared \
                      --with-gnu-as \
                      --with-gnu-ld \
		      --disable-nls \
                      --disable-werror \
                      --with-system-zlib \
	 	     ${GCCFLAGS}
    log "Building ${GCC}"
    ${MAKE} ${MAKEFLAGS}
    doinstall ${GCC} install
    cd ..
    log "Cleaning up ${GCC}"
    touch ${STAMPS}/${GCC}.build
    rm -rf build/* ${GCCDIR}
fi

if [ ! -e ${STAMPS}/${GDB}.build ]; then
    unpack ${GDB}
    cd build
    log "Configuring ${GDB}"
    ../${GDB}/configure --target=${TARGET} \
                      --prefix=${PREFIX} \
                      --enable-interwork \
                      --enable-multilib \
                      --disable-werror \
		      ${GDBFLAGS}
    log "Building ${GDB}"
    ${MAKE} ${MAKEFLAGS}
    doinstall ${GDB} install
    cd ..
    log "Cleaning up ${GDB}"
    touch ${STAMPS}/${GDB}.build
    rm -rf build/* ${GDB}
fi

if [ ${SUMMON_DIR_CREATED} = 1 ]; then
    log "Removing work directory"
    rm -rf ${SUMMON_DIR}
fi
